# Generated by Django 5.0.6 on 2024-06-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=40)),
                ('smarks', models.CharField(max_length=30)),
                ('saddr', models.CharField(max_length=100)),
            ],
        ),
    ]
